### ISSUE TITLE
Warning from Pandas when using FisherMatrix

### ISSUE THREAD

**Issue by dylancromer** [msyriac/orphics#20]
When instantiating a new FisherMatrix instance, I observe the warning
```
/Users/dylan/Development/orphics/orphics/stats.py:204: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
```

I have not seen this warning in past versions of orphics, and I have also not yet investigated whether this has any consequences, but I wanted to bring it to your attention. I am using Pandas 0.24.0.

**Comment by msyriac** [comment]
As far as I know, that warning appears whenever you do the following on a DataFrame object df:

`df.some_new_param_name = something
`
Since FisherMatrix subclasses DataFrame, it inherits this warning. The warning is saying "don't assume you have created a new column in the dataframe just because you added a new attribute". But I think that is ok. I do:

`self.params = param_list
`
and I don't intend self.params to be a new column, but simply a way for FisherMatrix to keep track of what parameter names are to be associated with each column.

Now we could get rid of self.params altogether since that is the only new attribute added by this class and it is redundant with self.columns.to_list(). But as you can do, I do an assert that checks that self.params and self.columns.to_list() are the same, to make sure the DataFrame structure hasn't changed with pandas versions, so I think it's safer to have this redundancy. I have added one more consistency check with b6543e91d0de8d84554feb243561d736c5a028bf to make sure self.params is not something that base DataFrames already come with. (Let me know if this breaks anything further)

**Comment by dylancromer** [comment]
Ok, it looks like this almost certainly causes no problems then. I will close this issue for now. Thanks!
